# Generated by Django 5.0 on 2023-12-17 20:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_bid_alter_listing_starting_bid'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item', to='auctions.listing'),
        ),
        migrations.AddField(
            model_name='bid',
            name='starting_bid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='start', to='auctions.listing'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='starting_bid',
            field=models.FloatField(default=0),
        ),
    ]
