# Generated by Django 5.0 on 2023-12-17 21:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0015_category_bid_bid_bid_user_listing_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item', to='auctions.listing'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='starting_bid',
            field=models.FloatField(default=0),
        ),
    ]
