# Generated by Django 5.0 on 2023-12-18 19:28

import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0016_bid_item_alter_listing_starting_bid'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='time',
            field=models.DateTimeField(db_default=django.db.models.functions.datetime.Now()),
        ),
        migrations.AddField(
            model_name='listing',
            name='time',
            field=models.DateTimeField(db_default=django.db.models.functions.datetime.Now()),
        ),
    ]
